version: '3.9'

services:
  db:
    image: mysql
    container_name: container_mysql-mindcare
    restart: always
    environment:
      - MYSQL_USER=mindcare
      - MYSQL_DATABASE=mindcare
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3307:3306
    networks:
      - net-mindcare
    volumes:
      - my-db:/var/lib/mysql

networks:
  net-mindcare:
    driver: bridge

volumes:
  my-db: